import React from 'react'
import Image from 'next/image'
import WikiLink from '../../../../../components/wiki/wiki-link'

const ShogunatePage = (): React.JSX.Element => {
  return (
    <div className="container mx-auto my-10">
      <h1 className="text-3xl text-blue-700 mb-10">Kogane Shogunate</h1>
      <h3 className="text-xl mb-5">Author: Shogun Eternicus</h3>
      <h2 className="text-2xl mb-5">Lore</h2>
      <p>An isolationist island nation found on the far Southern fringes of its former Empire. The Kogane Shogunate is a black sheep amongst the progressive counterparts of the world. It adheres to none of the cultural standards that are found within the Imperium, The Orchard, or Beangapore. Founded within the fires of the Sengoku period after the collapse of the Kogane Empire. the Kogane Empire was the largest Empire in ancient history before the Empire&apos;s collapse. Samurai and Kogane warriors were considered the finest soldiers of the world before its collapse. The modern Shogunate has a strict caste and class system and those borne into a caste have a hard time moving around in society. Even looking upon a noble in an impolite manner is just cause for death. (Though such punishments are rare in modern times). The land is ruled militarily by the <WikiLink href="../people/shogun">Shogun</WikiLink> and their Daimyo&apos;s. The Emperor of the Kogane Empire used to hold supreme power over the Shogun, but upon the collapse of the Kogane Empire it is a relatively forgotten position that is now filled in by the Shogun. The Isolationist nature of the Shogunate is caused from the collapse of the Kogane Empire and ensuing Sengoku period that lasted several hundred years as a result of there being no centralized Emperor to dictate what is to happen and a near total breakdown of Kogane&apos;s society occurred. Only the military might of the Shogun was enough to reunite the country into a stable realm that is by in large isolationist. Foreigners are looked down upon and are only given meager living standards if they are not outright executed. During the early days of the Shogunate in the Sengoku period, foreigners were allowed within the Shogunate but due to the influence of western religion and several religious uprisings caused by western religion, all the clergy and their followers were executed and centralized religion banned.</p>
      <Image src="/kogane.jpg" alt="kogane art" height={300} width={500} className="inline" />
      <Image src="/kogane_bannerr.jpg" alt="kogane banner" height={300} width={150} className="inline ml-5" />
      <h2 className="text-2xl my-5">Modern Geopolitics</h2>
      <p>
        The modern situation of the Kogane Shogunate is one of Sakoku. <strong><em>Sakoku</em></strong> (鎖国 - Meaning &apos;chained country&apos;) is the isolationist foreign policy of the Kogane Shogunate under which, for continuous period of 265 years during the Sengoku period, relations and trade between Kogane and other countries are severely limited, and nearly all foreign nationals are banned from entering Kogane, while common Koganese people are kept from leaving the country. The policy was enacted by the Shogunate government (or bakufu (幕府)) under Shogun Eternicus through a number of edicts and policies from Inception to the modern period of the Shogunate. In order to avoid the wrath of other nations, the Shogunate purposefully avoids contact with other nations and isolates itself accordingly. This is to ensure the longevity of the Shogunate and its people.
      </p>
      <p>
        With the introduction of modern technology, the Shogunate has become one of the most prosperous nations within the realm. The introduction of modern technology but traditionalist culture is pervasive as title feuds are commonplace.
      </p>
      <p>
        Relations with other nations are minimal. The <WikiLink href="imperium">Imperium</WikiLink> is considered the Shogunate&apos;s largest trading partner as both nations have mutualistic and symbiotic understandings of each others cultures. So much so, that <WikiLink href="../people/meme">Emperor Meme</WikiLink> is considered a Ronin within the Shogunate and has been allowed within the very halls of Seong (성). The Imperium understands and respects the desire of a everlasting serenity that the Shogunate pursues. Relations with <WikiLink href="orchard">The Orchard</WikiLink> are indifferent at best, tense at worst. <WikiLink href="../people/farmer">Farmer Rosey</WikiLink> is viewed as a destabilizing element to the status quo and as such is viewed with suspicion. <WikiLink href="beangapore">Beangapore</WikiLink> is viewed indifferently.
      </p>
      <h2 className="text-2xl my-5">Modern Culture</h2>
      <p>The Shogunate continues to be an isolationist nation but has allowed a foreign free-port where Foreigners are allowed to be within and own land for diplomatic purposes. They are bound by the laws set out by the local Daimyo and what the local Daimyo or the Shogun themselves says is law. The Shogunate is a traditional warrior culture that very commonly has civil wars over honor and title feuds. To fight and die in combat is considered honorable to the family clan&apos;s and is the cause for many civil wars. Service to Community, Family, and Tradition is viewed as the highest honor if one is to not die in combat. Service to ones family is viewed as a great honor. To be charitable to one another in the community is viewed as commonplace. Men typically serve in military, trades, farming, artisan, and political roles. Women typically serve in administrative, medical, educational, religious, and child care roles. The recent establishment of the Free-port has caused trade to open up although trade is usually a one sided affair as the Kogane Shogunate rarely imports foreign materials and has a tendency to only export their goods. Foreigners are tolerated at the free-port and as such they are expected to stay at the Free-port due to past histories of Foreigners not respecting the culture and political dynamics of Kogane.</p>
      <h2 className="text-2xl my-5">Law</h2>
      <p>Most laws within the Kogane Shogunate are aimed at foreigners / foreign goods and not citizens. Citizens within the Shogunate adhere to strict cultural standards and as such do not require laws to moderate their behavior. Foreigners are not allowed outside of the freeport and if they are found outside a freeport, they will be brutally beaten and deported. Resistance to deportation will result in execution. An insult against even a lowly commoner by a foreigner is the equivalent to insulting the shogun themselves. Even being impolite to the Shogun on Kogane soil is just cause for being tossed out or executed for a foreigner. (Though such punishments are rarely dealt out.)</p>
      <ul className="list-disc ml-10">
        <li>Religions that are not native to the Kogane Shogunate are banned outright due to religious uprisings.</li>
        <li>Slavery is banned as it is viewed as dishonorable to the citizenry of the Kogane Shogunate. Religion within the Shogunate is less centralized and more philosophical as it adheres more an equivalent of ancestor worship with various monks and shrine maidens bestowing blessings upon commoners for good vitality and good fortune.</li>
      </ul>
      <h2 className="text-2xl my-5">Caste System</h2>
      <p>Emperor = Monarch (Unfilled position due to collapse of Kogane Empire)<br />Shogun = Monarch / Duke (Holds actual power)<br />Daimyo = Duke (Wealthy land owners)<br />Samurai = Knight / Militarized Baronet (Samurai didnt own land from a lord, receives income from local lords)<br />Ronin = Knight / Gentlemen (Samurai that either lost favor with Daimyo or their Daimyo died.)<br />Commoner/ Peasant = Freeman/ Yeoman (produce core goods. Have no real social mobility.)<br />Artisan = Yeoman/ Freeman (Actually produced high quality goods but were considered lower class)<br />Merchant = Merchant (Lowest class because they produced nothing on their own)<br />Foreigner - Not welcome to the shogunate and will be quickly deported back to the Freeport, is lower than a Merchant.</p>
      <h2 className="text-2xl my-5">Language</h2>
      <p>There are three spoken languages within the Shogunate and one written language. Each spoken language has hundreds of dialects as a result of the Sengoku period and the fracturing of the Shogunate until the first Shogun reunited Kogane into what it is today. Modern written Koganese has one written alphabet (한국어). The three spoken languages are as follows.<br />日本語 - Is ancient Koganese, spoken by the nobility and is considered old as its alphabet is rarely used anymore. It would be the equivalent to Latin.<br />漢字 - Is spoken by old clans and older generations and is considered old fashioned to speak it. It is a rarely taught language anymore. It would be the equivalent to 1500&apos;s English.<br />한국어 - Is modern Koganese used by everyone to communicate to each other from the highest noble to the lowest commoner. It would be the equivalent to modern English.<br />中國人 - Foreigners are purposefully taught a fourth language as to differentiate them from a native citizen. Foreigners are not allowed to learn modern Koganese for military purposes.</p>
    </div>
  )
}

export default ShogunatePage
